name: Commit Manual para Fixar Contribuições

on:
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Configurar usuário Git
        run: |
          git config --global user.name "LukeX404"
          git config --global user.email "lucasneko25@gmail.com"

      - name: Commit & Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Commit manual 4 fix commits"